const items=[
    "Peace",
    "Trust",
    "Confidence",
    "Self-Control",
    "Motivation",
    "Discipline",
    "Consistency",
    "Persistent",
    "Accuracy",
    "Boundaries",
    "Self-acceptance",
    "Self-compassion",
    "Fear of Failure",
    "Acceptance",
    "Values",
    "Goals",
    "Routine",
    "Prioritization",
    "Time Management",
    "Health",
    "Responsibility",
    "Deadlines",
  ]
export default items;